// <auto-generated />
using System;
using DCAPPLIB.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250712113237_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ClinicalCustomer", b =>
                {
                    b.Property<int>("ClinicalsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClinicalsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("ClinicalCustomer");
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Clinical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clinicals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Klinik 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Klinik 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Klinik 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Klinik A1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Klinik A2"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Klinik B1"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Klinik B2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klinik C1"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Klinik C2"
                        });
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Dentist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalId");

                    b.ToTable("Dentists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicalId = 3,
                            FirstName = "Umut Berk",
                            LastName = "Demir"
                        },
                        new
                        {
                            Id = 2,
                            ClinicalId = 1,
                            FirstName = "Elif Naz",
                            LastName = "Yıldız"
                        },
                        new
                        {
                            Id = 3,
                            ClinicalId = 5,
                            FirstName = "Mert Can",
                            LastName = "Koç"
                        },
                        new
                        {
                            Id = 4,
                            ClinicalId = 2,
                            FirstName = "Zeynep",
                            LastName = "Aydın"
                        },
                        new
                        {
                            Id = 5,
                            ClinicalId = 4,
                            FirstName = "Ali Eren",
                            LastName = "Şahin"
                        },
                        new
                        {
                            Id = 6,
                            ClinicalId = 1,
                            FirstName = "Ayşe",
                            LastName = "Kara"
                        },
                        new
                        {
                            Id = 7,
                            ClinicalId = 5,
                            FirstName = "Emirhan",
                            LastName = "Yılmaz"
                        },
                        new
                        {
                            Id = 8,
                            ClinicalId = 3,
                            FirstName = "Melisa",
                            LastName = "Çelik"
                        },
                        new
                        {
                            Id = 9,
                            ClinicalId = 2,
                            FirstName = "Berkay",
                            LastName = "Arslan"
                        },
                        new
                        {
                            Id = 10,
                            ClinicalId = 4,
                            FirstName = "İlayda",
                            LastName = "Öztürk"
                        },
                        new
                        {
                            Id = 11,
                            ClinicalId = 2,
                            FirstName = "Deniz",
                            LastName = "Aksoy"
                        },
                        new
                        {
                            Id = 12,
                            ClinicalId = 1,
                            FirstName = "Kaan",
                            LastName = "Bozkurt"
                        });
                });

            modelBuilder.Entity("ClinicalCustomer", b =>
                {
                    b.HasOne("DCAPPLIB.Entities.Clinical", null)
                        .WithMany()
                        .HasForeignKey("ClinicalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCAPPLIB.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Appointment", b =>
                {
                    b.HasOne("DCAPPLIB.Entities.Customer", null)
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Dentist", b =>
                {
                    b.HasOne("DCAPPLIB.Entities.Clinical", "Clinical")
                        .WithMany("Dentists")
                        .HasForeignKey("ClinicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinical");
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Clinical", b =>
                {
                    b.Navigation("Dentists");
                });

            modelBuilder.Entity("DCAPPLIB.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
